# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

# 参考
# https://sheldon.cli.rs/Examples.html
# https://ryota2357.com/blog/2022/zsh-plugmanager-zplug-to-sheldon/

# 起動速度の測定
# `time ( zsh -i -c exit )`

shell = "zsh"

# デフォルトを遅延読み込みにする
apply = ["defer"]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[templates]
# 遅延読み込みのテンプレート
# source テンプレートを zsh-defer しているだけ。
# https://github.com/rossmacarthur/sheldon?tab=readme-ov-file#templates
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

# コマンドの自動補完
# fzf-tab と 相性が悪いので使用していない。
# [plugins.zsh-autocomplete]
# github = "marlonrichert/zsh-autocomplete"

# コマンドのシンタックスハイライト
[plugins.syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

# コマンドの自動サジェスチョン
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

# 色んなコマンドの補完のセット
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

# タプで補完を選択
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

# abbreviations
[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.zsh-autosuggestions-abbreviations-strategy]
github = "olets/zsh-autosuggestions-abbreviations-strategy"

# Git Objects を fzf で選択
# https://github.com/junegunn/fzf-git.sh
[plugins.fzf-git]
github = "junegunn/fzf-git.sh"
use = ["fzf-git.sh"]

# コマンドの completion を有効にする
[plugins.compinit]
inline = 'autoload -Uz compinit && zsh-defer compinit'
