[firefox]
# Add Emacs-style cursor movement to the existing Control layer.
control.b=left
control.f=right
control.p=up
control.n=down
control.a=home
control.e=end
control.h=backspace
control.d=delete
control.k=macro(S-end delete)

control+shift.b = C-b
control+shift.f = C-f
control+shift.p = C-p
control+shift.n = C-n
control+shift.a = C-a
control+shift.e = C-e
control+shift.h = C-h
control+shift.d = C-d
control+shift.k = C-k


[dev-noctalia-noctalia]
# Add Emacs-style cursor movement to the existing Control layer.
control.b=left
control.f=right
control.p=up
control.n=down
control.a=home
control.e=end
control.h=backspace
control.d=delete
control.k=macro(S-end delete)

control+shift.b = C-b
control+shift.f = C-f
control+shift.p = C-p
control+shift.n = C-n
control+shift.a = C-a
control+shift.e = C-e
control+shift.h = C-h
control+shift.d = C-d
control+shift.k = C-k
