[firefox]
# Add Emacs-style cursor movement to the existing Control layer.
control.b=left
control.f=right
control.p=up
control.n=down
control.a=home
control.e=end
control.h=backspace
control.d=delete
control.k=macro(S-end delete)
control.m=enter
control.g=esc

[dev-noctalia-noctalia]
# Add Emacs-style cursor movement to the existing Control layer.
control.b=left
control.f=right
control.p=up
control.n=down
control.a=home
control.e=end
control.h=backspace
control.d=delete
control.k=macro(S-end delete)
control.m=enter
control.g=esc
