[firefox]
# Add Emacs-style cursor movement to the existing Control layer.
control.b=left
control.f=right
control.p=up
control.n=down
control.a=home
control.e=end
control.h=backspace
control.d=delete
control.k=macro(S-end delete)

alt.b   = C-b
altgr.b = C-b
alt.f   = C-f
altgr.f = C-f
alt.p   = C-p
altgr.p = C-p
alt.n   = C-n
altgr.n = C-n
alt.a   = C-a
altgr.a = C-a
alt.e   = C-e
altgr.e = C-e
alt.h   = C-h
altgr.h = C-h
alt.d   = C-d
altgr.d = C-d
alt.k   = C-k
altgr.k = C-k


[dev-noctalia-noctalia]
# Add Emacs-style cursor movement to the existing Control layer.
control.b=left
control.f=right
control.p=up
control.n=down
control.a=home
control.e=end
control.h=backspace
control.d=delete
control.k=macro(S-end delete)
