theme = "catppuccin_mocha"

[editor]
color-modes = true
bufferline = "always"
trim-final-newlines = true
trim-trailing-whitespace = true
line-number = "relative"
cursorline = true
default-yank-register = "+"

[editor.indent-guides]
render = true

[editor.auto-save]
focus-lost = true

[editor.statusline]
left = [
  "mode",
  "spinner",
  "version-control",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator"
]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "file-encoding",
  "file-indent-style",
  "file-type"
]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = false

[editor.file-picker]
hidden = false

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
A-r = ":reload-all"

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
