# https://github.com/blopker/codebook
[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "markdown"
language-servers = ["codebook"]

[[language]]
name = "bash"
formatter = { command = "shfmt" }
auto-format = true
