# https://github.com/yazi-rs/plugins/tree/main/vcs-files.yazi
[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "plugin vcs-files"
desc = "Show Git file changes"

# https://github.com/Lil-Dank/lazygit.yazi
[[mgr.prepend_keymap]]
on = "<C-g>"
run = "plugin lazygit"
desc = "run lazygit"

# https://github.com/XYenon/clipboard.yazi
# Copy yanked files to the system clipboard
[[mgr.prepend_keymap]]
on = "y"
run = ["yank", "plugin clipboard -- --action=copy"]
desc = "Yank selected files (copy)"

# Keep behaviour consistent with cut
[[mgr.prepend_keymap]]
on = "x"
run = ["yank --cut", "plugin clipboard -- --action=copy"]
desc = "Yank selected files (cut)"

# Paste files from the system clipboard into the current directory
[[mgr.prepend_keymap]]
on = "<C-p>"
run = ["plugin clipboard -- --action=paste"]
desc = "Paste yanked system clipboard files"
