[bar.default]
concave_edge_corners = false
margin_ends = 10
# center = ["clock", "cat"]
end = [
  "media",
  "tray",
  "notifications",
  "screenshot",
  "recorder",
  "clipboard",
  "network",
  "bluetooth",
  "volume",
  "brightness",
  "battery",
  "control-center",
  "session"
]
