[plugins]
enabled = [
  "noctalia/translator",
  "noctalia/screen_recorder",
  "noctalia/bongocat"
]

[plugin_settings."noctalia/translator"]
target_lang = "ja"

[plugin_settings."noctalia/screen_recorder"]
audio_codec = "aac"
copy_to_clipboard = true
frame_rate = 30
video_codec = "hevc"
