[shell]
launch_apps_as_systemd_services = true  # launch apps as transient systemd scopes

[keybinds]
cancel = ["escape", "ctrl+c"]
left = ["left", "ctrl+h"]
right = ["right", "ctrl+l"]
up = ["up", "ctrl+k"]
down = ["down", "ctrl+j"]
