format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

# right_format = """$time"""

[directory]
style = "bold blue"
truncation_length = 0
# truncate_to_repo = false

[character]
# success_symbol = "[❯](purple)"
# error_symbol = "[❯](red)"
# vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
modified = "[M](yellow)"
staged = "[A](green)"
untracked = "[?](red)"
deleted = "[D](red)"
renamed = "[R](blue)"
conflicted = "[!](red bold)"
stashed = "[≡](cyan)"

[cmd_duration]
min_time = 0
show_milliseconds = true
format = "[$duration]($style) "
style = "yellow"

[time]
disabled = false
format = '[$time]($style) '
time_format = '%c'
